//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class News_AggregatorEntities : DbContext
    {
        public News_AggregatorEntities()
            : base("name=News_AggregatorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<NewsWorkFlow> NewsWorkFlows { get; set; }
        public virtual DbSet<Recommendation> Recommendations { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<NewsTag> NewsTags { get; set; }
        public virtual DbSet<ReporterRating> ReporterRatings { get; set; }
        public virtual DbSet<NewsPopularity> NewsPopularities { get; set; }
        public virtual DbSet<ReaderActivity> ReaderActivities { get; set; }
        public virtual DbSet<UserPassword> UserPasswords { get; set; }
    }
}
