//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsPopularity
    {
        public int ID { get; set; }
        public int NID { get; set; }
        public int OpenCnt { get; set; }
        public int ShareCnt { get; set; }
        public Nullable<double> PopularityScore { get; set; }
        public int LikeCnt { get; set; }
    
        public virtual News News { get; set; }
    }
}
