//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsWorkFlow
    {
        public int ID { get; set; }
        public int NewsID { get; set; }
        public string Action { get; set; }
        public int ActionBy { get; set; }
        public System.DateTime ActionDate { get; set; }
    
        public virtual News News { get; set; }
        public virtual User User { get; set; }
    }
}
